include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
