// AI Shift Summary — Supabase Edge Function (Phase 5 #31 / B8)
//
// Receives the shift's care records (already gathered client-side from the
// same providers that power the handover screen) and returns a written
// handover brief generated by Claude. The Anthropic API key lives only in
// this function's secrets — it is never shipped in the app.
//
// Deploy:
//   supabase functions deploy ai-shift-summary
//   supabase secrets set ANTHROPIC_API_KEY=sk-ant-...
//
// Auth: the platform verifies the Supabase JWT (verify_jwt defaults to on).
// On top of that we gate by role — only team leaders and managers run
// handover — and require AAL2 for managers, mirroring the
// require_mfa_for_privileged_roles RLS policy.

import Anthropic from "npm:@anthropic-ai/sdk";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/** Decodes the (platform-verified) JWT payload without re-verifying. */
function jwtClaims(authHeader: string | null): Record<string, unknown> {
  try {
    const token = authHeader?.replace(/^Bearer\s+/i, "") ?? "";
    const payload = token.split(".")[1];
    return JSON.parse(atob(payload.replace(/-/g, "+").replace(/_/g, "/")));
  } catch {
    return {};
  }
}

const SYSTEM_PROMPT = `You write shift handover briefs for a UK children's
residential care home. You receive structured records from one shift —
daily notes, behaviour incidents (ABC model), incident reports, medication
administrations, and bath temperature checks — and produce a clear,
professional brief for the incoming shift team.

Rules:
- Use only the information provided. Never invent, infer, or embellish
  details. If a section has no records, say so in one short line.
- Lead with anything safety-critical: safeguarding concerns, physical
  interventions, injuries, medication refusals, high/critical incidents.
- Then summarise per child, in plain British English, in the order given.
- Be specific: include times, medication names and outcomes, and who
  recorded what, when that information is present.
- Keep it scannable: short paragraphs or bullet points, bold child names.
- Close with anything the incoming shift must follow up on.
- This is a confidential care record. Maintain a respectful, factual tone
  about the children at all times.`;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }
  if (req.method !== "POST") {
    return json({ error: "Method not allowed" }, 405);
  }

  // Role gate — handover is a team leader / manager surface.
  const claims = jwtClaims(req.headers.get("Authorization"));
  const role = claims["app_role"] as string | undefined;
  const aal = claims["aal"] as string | undefined;
  if (role !== "team_leader" && role !== "manager") {
    return json({ error: "Forbidden: handover summaries are limited to team leaders and managers" }, 403);
  }
  if (role === "manager" && aal !== "aal2") {
    return json({ error: "Forbidden: complete the MFA challenge first" }, 403);
  }

  const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
  if (!apiKey) {
    return json({ error: "ANTHROPIC_API_KEY secret is not configured" }, 500);
  }

  let payload: { date?: string; shift?: string; children?: unknown[] };
  try {
    payload = await req.json();
  } catch {
    return json({ error: "Invalid JSON body" }, 400);
  }
  if (!payload.children || payload.children.length === 0) {
    return json({ error: "No shift records provided" }, 400);
  }

  const anthropic = new Anthropic({ apiKey });

  try {
    const response = await anthropic.messages.create({
      model: "claude-opus-4-8",
      max_tokens: 4000,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: "user",
          content:
            `Write the handover brief for the ${payload.shift ?? "current"} ` +
            `shift on ${payload.date ?? "today"}. Shift records follow as ` +
            `JSON:\n\n${JSON.stringify(payload.children)}`,
        },
      ],
    });

    if (response.stop_reason === "refusal") {
      return json({ error: "The summary request was declined. Try again." }, 502);
    }

    const summary = response.content
      .filter((block) => block.type === "text")
      .map((block) => (block as { text: string }).text)
      .join("\n");

    if (!summary) {
      return json({ error: "Empty response from the model" }, 502);
    }
    return json({ summary });
  } catch (error) {
    // The real reason (low credit, invalid key, bad request, model id, …)
    // is logged here for ops/admins. Dashboard → Edge Functions → Logs.
    console.error("Anthropic call failed:", error);

    // Rate limiting is the one case care staff can act on — wait and retry.
    if (error instanceof Anthropic.RateLimitError) {
      return json({
        error: "The AI service is busy right now — please try again in a minute.",
      }, 429);
    }

    // Auth, billing, and other config failures aren't staff-actionable.
    // Show a generic line and point them at an administrator; the specific
    // cause stays in the function logs above.
    const status = error instanceof Anthropic.APIError ? 502 : 500;
    return json({
      error: "AI summary is temporarily unavailable. Please contact your administrator.",
    }, status);
  }
});
